stages:
    - server-lint
    - server-deploy
    - client-lint
    - client-deploy

server_lint_inspection:
    stage: server-lint
    script:
      - cd /server
      - npm install
      - npm run lint
      - npm run test-controller
    tags:
    - shell

server_deploy_Only_master:
  stage: server-deploy
  only:
    - master
  script:
    - cp $ENV ./.env
    - docker stop $(docker ps -a -q)
    - docker rm $(docker ps -a -q)
    - docker rmi $(docker images -q)
    - docker build --tag server:node -f Dockerfile .
    - docker run -id -p 5000:5000 server:node
  tags:
    - shell

client_lint_inspection:
    stage: client-lint
    script:
        - cd /client
        - npm run lint
    tags:
        - shell

client_deploy_Only_master:
    stage: client-deploy
    only:
        - master
    script:
        - cp $ENV ./.env
        - docker stop $(docker ps -a -q)
        - docker rm $(docker ps -a -q)
        - docker rmi $(docker images -q)
        - docker build --tag client:react -f Dockerfile.dev .
        - docker run -id -p 80:80 client:react
    tags:
        - shell

