image: node:latest

stages:
    - client-build
    - client-lint

before_script:
    - export PATH=$PATH:/usr/local/bin
    - npm install

client_build_test:
    stage: client-build
    script:
        - npm run build
    tags:
        - react

client_lint_inspection:
    stage: client-lint
    script:
        - npm run lint
    tags:
        - react

