image: node:latest

stages:
    - client-build
    - client-lint
    - client-deploy

client_build_test:
    stage: client-build
    before_script:
        - npm install
    script:
        - npm run build
    tags:
        - react

client_lint_inspection:
    stage: client-lint
    script:
        - npm run lint
    tags:
        - react

client_deploy_Only_master:
    stage: client-deploy
    script:
        - sudo docker build --tag client:react -f Dockerfile.dev .
        - sudo docker run -it -p 80:80 client:react
    tags:
        - react
