services:
    - mongo:latest

stages:
    - server-lint

server_lint_inspection:
    stage: server-lint
    before_script:
    - export PATH=$PATH:/usr/local/bin
    only:
        variables:
          - $DB_SCHEMA
          - $DB_URL
          - $DB_USER
          - $DB_PASSWORD
          - $DB_HOST
          - $DB_PORT
    script:
    - npm install
    - npm run lint
    tags:
    - moneydog

