services:
    - mongo:latest

stages:
    - client-lint

client_lint_inspection:
    stage: client-lint
    before_script:
        - export PATH=$PATH:/usr/local/bin
    script:
        - npm install
        - npm run lint
    tags:
        - moneydog
