image: node:latest

stages:
    - build
    - lint

default:
    before_script:
        - npm install
        - export PATH=$PATH:/usr/local/bin

client_build_test:
    stage: build
    script:
        - echo 'client build start'
        - npm run build
    tags:
        - client

client_lint_test:
    stage: lint
    script:
        - echo 'client lint start'
        - npm run lint
    tags:
        - client

