image: node:latest

stages:
    - client-build
    - client-lint

client_build_test:
    stage: client-build
    before_script:
        - export PATH=$PATH:/usr/local/bin
        - npm install
    script:
        - npm run build
    tags:
        - react


client_lint_inspection:
    stage: client-lint
    script:
        - npm run lint
    tags:
        - react
