image: gitlab-registry

stages:
    - server-lint
    - client-lint

server_lint_inspection:
    stage: server-lint
    before_script:
    - export PATH=$PATH:/usr/local/bin
    script:
    - cd server
    - npm install
    - npm run lint
    - npm run test-subs-repo
    tags:
    - moneydog

client_lint_inspection:
    stage: client-lint
    before_script:
    - export PATH=$PATH:/usr/local/bin
    script:
    - cd client
    - npm install
    - npm run lint
    tags:
    - moneydog