
stages: 
    - client-build
    - client-lint
    - client-deploy

client_build_test:
    stage: client-build
    before_script:
        - echo $REACT_ENV
        - npm install
    script:
        - npm run build
    tags:
        - shell

client_lint_inspection:
    stage: client-lint
    script:
        - npm run lint
    tags:
        - shell

client_deploy_Only_master:
    stage: client-deploy
    only:
        - master
    script:
        - docker stop $(docker ps -a -q)
        - docker rm $(docker ps -a -q)
        - docker rmi $(docker images -q)
        - docker build --tag client:react -f Dockerfile.dev .
        - docker run -id -p 80:80 client:react
    tags:
        - shell

