version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10 # the primary container, where your job's commands are run
    environment:
      REACT_APP_NODE_API_URL: $REACT_APP_NODE_API_URL
      REACT_APP_IMAGE_URI: $REACT_APP_IMAGE_URI
      DB_SCHEMA: $DB_SCHEMA
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      PROD_DB_URL: $PROD_DB_URL
      DEV_DB_URL: $DEV_DB_URL
      TEST_DB_URL: $TEST_DB_URL
      MIGRATE_dbConnectionUri: $MIGRATE_dbConnectionUri
      JWT_SECRET: $JWT_SECRET
      GOOGLE_API_CLIENT_ID: $GOOGLE_API_CLIENT_ID
      GOOGLE_API_CLIENT_SECRET: $GOOGLE_API_CLIENT_SECRET
      GOOGLE_API_REDIRECT_URL: $GOOGLE_API_REDIRECT_URL
      GOOGLE_API_SCOPE: $GOOGLE_API_SCOPE
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: node_module install
          command: 'npm install'
      - run:
          name: check lint
          command: 'npm run lint'
      - run:
          name: running test
          commnad: 'npm run test'
      - run:
          name: make build file
          command: 'npm run build'
      - run:
          name: npm run build success
          command: 'echo success'
