# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2 # use circleCI version2.0
jobs:
  build:
    branches:
      only:
        - dev
        - jy-issue-37
    docker:
      # specify the version you desire here
      - image: circleci/node:8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/server

    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm i -g npm@latest'
      # Download and cache dependencies
#      - restore_cache:
#          keys:
#            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
#            - v1-dependencies-

      - run:
          name: install node modules
          command: npm install
#      - run:
#          name: ESLing, write report
#          command: |
#            mkdir -p ~/reports
#            eslint . --ext .js --output-file ~/reports/eslint.xml

#      - save_cache:
#          paths:
#            - ./node_modules
#          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: npm test
