image: node:latest

stages:
    - lint

eslint:
    only:
    - yh-issue-42
    stage: lint
    script:
        - echo eslint start
        - npm install -g eslint
        - eslint --init
        - eslint app.js