swagger: "2.0"
info:
  title: "MoneyDog Server API"
  version: "1.0.0"
  description: "'Client', 'Google API' 서버와 통신을 위한 REST API 문서"
  contact:
    email: "moneydog@gmail.com"
host: "localhost:5000"
basePath: /
tags:
  - name: user
    description: 사용자 정보
  - name: subscription
    description: 구독 서비스 정보 
schemes:
  - http
  - https
paths:
  /subscriptions:
    get:
      tags:
        - subscription
      summary: 우리가 수집한 구독 서비스 목록
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: success
          schema:
            type: array
            items:
              type: string
        "400":
          description: Invaild status value
    post:
      tags:
        - subscription
      summary: Add a new user subscriptions info
      parameters:
        - in: body
          name: body
          description: Pet object that needs to be added to the store
          required: false
          schema:
            $ref: "#/definitions/SelectedSubscription"
      responses:
        "405":
          description: Invalid input
definitions:
  SelectedSubscription:
    properties:
      id:
        type: string
      name:
        type: string
  